import { TenderQA } from "../types";

export const generateWordDocument = (results: TenderQA[], originalFilename: string = "Tender_Response") => {
  if (!window.docx || !window.saveAs) {
    const msg = "Export libraries are not fully loaded. Please check your internet connection and refresh the page.";
    console.error("Export libraries not loaded", { docx: !!window.docx, saveAs: !!window.saveAs });
    alert(msg);
    return;
  }

  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = window.docx;

  const children = [
    new Paragraph({
      text: `Tender Response Draft`,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 }
    }),
    new Paragraph({
      text: `Generated by PSL-Auto on ${new Date().toLocaleDateString()}`,
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 }
    }),
    new Paragraph({
        text: `Source File: ${originalFilename}`,
        alignment: AlignmentType.CENTER,
        spacing: { after: 600 },
        children: [new TextRun({ text: "", italics: true, size: 16 })]
    })
  ];

  results.forEach((item, index) => {
    // Question
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Q${index + 1}: ${item.question}`,
            bold: true,
            size: 24, // 12pt
            color: "0f172a" // Navy
          })
        ],
        spacing: { before: 300, after: 100 }
      })
    );

    // Answer
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: item.answer,
            size: 22, // 11pt
            color: "334155" // Slate-700
          })
        ],
        spacing: { after: 300 }
      })
    );

    // Separator (Empty line with border logic if needed, or just spacing)
    children.push(
      new Paragraph({
        text: "",
        border: { bottom: { color: "e2e8f0", space: 1, value: "single", size: 6 } },
        spacing: { after: 200 }
      })
    );
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children: children,
    }],
  });

  const dateStr = new Date().toISOString().split('T')[0];
  // Clean up filename for export
  const cleanName = originalFilename.replace(/\.[^/.]+$/, "").replace(/\s+/g, "_");
  
  Packer.toBlob(doc).then((blob: Blob) => {
    window.saveAs(blob, `${cleanName}_Response_${dateStr}.docx`);
  });
};